# Generated by Django 3.2.8 on 2021-10-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='army',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RenameField(
            model_name='army',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='army',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
