# Generated by Django 3.2.8 on 2021-10-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211012_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Miniatures', to='main_app.army')),
            ],
        ),
    ]
