# Generated by Django 3.2.7 on 2021-11-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini',
            name='army',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minis', to='main_app.army'),
        ),
    ]
